# Generated by Django 5.2.5 on 2025-09-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_codee',
            new_name='postal_code',
        ),
    ]
